name: Flyway Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flyway CLI
        uses: red-gate/setup-flyway@v1
        with:
          version: '11.15.0'  # pinned to 11.15.0

      - name: Run Flyway Migrations
        run: flyway \
              --url="${{ secrets.DB_URL }}" \
              --user="${{ secrets.DB_USER }}" \
              --password="${{ secrets.DB_PASSWORD }}" \
              --locations=filesystem:./sql \
              migrate
